# This gets overridden when building for production
baseurl = "https://zvakt-shekn987.github.io/"
DefaultContentLanguage = "en"
title = "zꞵāktšēkn"
theme = "beautifulhugo"
enableGitInfo = true
timeZone = "UTC"
ignoreFiles = ["content/archive/.*"]

[pagination]
  pagerSize = 5

[Services]
  [Services.Disqus]
    # Shortname = "XXX"
  [Services.googleAnalytics]
    # id = "XXX"

[taxonomies]
  category = "categories"
  tag = "tags"

[Params]
  subtitle = "Pavillon des langues"
  mainSections = ["post", "recipe"]
  logo = "/img/ushtras.jpg" # Expecting square dimensions
  favicon = "/img/favicon.ico"
  dateFormat = "2006.02.01"
  commit = false
  rss = true
  readingTime = true
  wordCount = true
  colorScheme = "auto"
  # mathEngine = "katex"  # "katex" (default), "mathjax" (CDN only), or "none"
  socialShare = true
  delayDisqus = true
  showRelatedPosts = true
  disableFigureOverride = true
  headerImgStyle = "narrow"
  showSource = true
  sourceRepo = "https://github.com/halogenica/beautifulhugo/blob/master/exampleSite/"
  comment = "https://github.com/halogenica/beautifulhugo/commit/"

  [Params.search]
    provider = "fuse"

[[Params.bigimg]]
  src = "/img/jiphyonjon.jpg"
  desc = "Image courtesy of https://contents.history.go.kr"

[Params.AISearchSummary.Googlebot]
  summaryLimit = 0
[Params.AISearchSummary.robots]
  summaryLimit = 0

[Params.seo.robots]
  ai-summary-limit = "nosnippet"
  noindex = true
  nofollow = true

[Params.seo.GoogleBot]
  noindex = true
  ai-summary-limit = 0

[Params.author]
  name = "Nennius Nescius"
  website = "yourwebsite.com"
  email = "youremail@domain.com"
  github = "username"
  twitter = "username"
  linkedin = "in/username" # company/username

[markup.highlight]
  noClasses = false

[markup.goldmark.parser.attribute]
  block = true

[markup.goldmark.renderer]
  unsafe = true

[[menu.main]]
    identifier = "blog"
    name = "Blog"
    weight = 3

[[menu.main]]
    parent = "blog"
    name = "Posts"
    url = "post/"
    weight = 1

[[menu.main]]
    parent = "blog"
    name = "Tags"
    url = "tags/"
    weight = 2

[[menu.main]]
    parent = "blog"
    name = "Categories"
    url = "categories/"
    weight = 3

[[menu.main]]
    parent = "blog"
    name = "Archives"
    url = "archives/"
    weight = 4

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 4

[outputs]
home = ["HTML", "RSS", "JSON"]
section = ["HTML", "RSS", "JSON"]
page = ["HTML"]
